[package]
name = "rust-t"
version = "0.1.0"
authors = ["parkyes90 <parkyes90@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rand = "0.6.1"